uvmf:
  environments:
    lc3:
      agents:
      - initiator_responder: RESPONDER
        name: imem_resp
        type: imem
      - initiator_responder: RESPONDER
        name: dmem_resp
        type: dmem
      analysis_components: []
      analysis_exports: []
      analysis_ports: []
      config_constraints: []
      config_vars: []
      existing_library_component: 'True'
      hvl_pkg_parameters: []
      imports:
      - name: fetch_env_pkg
      - name: decode_env_pkg
      - name: execute_env_pkg
      - name: memaccess_env_pkg
      - name: writeback_env_pkg
      - name: control_env_pkg
      - name: dmem_pkg
      - name: imem_pkg
      - name: lc3_prediction_pkg
      non_uvmf_components: []
      parameters: []
      qvip_memory_agents: []
      scoreboards: []
      subenvs:
      - name: fetch_env
        parameters: []
        type: fetch
      - name: decode_env
        parameters: []
        type: decode
      - name: execute_env
        parameters: []
        type: execute
      - name: writeback_env
        parameters: []
        type: writeback
      - name: memaccess_env
        parameters: []
        type: memaccess
      - name: control_env
        parameters: []
        type: control
      tlm_connections: []
